name: offline_otlp_log_exporter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  queue: ^3.1.0+2
  intl: ^0.17.0
  collection: ^1.16.0
  fixnum: '>=1.0.0 <2.0.0'
  protobuf: '>=2.0.0 <4.0.0'
  http: '>=0.13.0 <2.0.0'
  opentelemetry:
    git:
      url: git@github.com:yuzurihaaa/opentelemetry-dart.git
      ref: 531696dae68055bd5a1d051d62c665bc0ff1fc6a

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
